name: Code Quality Check

on: [push]

jobs:
  CodeQualityCheck:
    name: Code Quality Check
    runs-on: [linux]
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install modules
        run: yarn

      - name: Run Linter
        run: yarn lint --no-cache

      - name: Run TS types check
        run: yarn tsc
